date.timezone=Asia/Shanghai
memory_limit=512M
upload_max_filesize=20M
post_max_size=25M
max_execution_time=300
default_socket_timeout=300
display_errors=Off
log_errors=On
error_log=/var/www/html/logs/php_errors.log

